bs_ubuntu_logo = 'Assets/Sprites/Extra1/Ubuntu/Ubuntu_pixian_ai.png'
# Images of blocks
bs_grass_block = 'Assets/Sprites/Grass/Normal.png'
bs_stone_block = 'Assets/Sprites/Blocks/Gray50.png'
bs_sponge_block = 'Assets/Sprites/Hellish/Plants/Sponge.png'
bs_ice_block = 'Assets/Sprites/Blocks/Turquoise.png'
bs_gray40_block = 'Assets/Sprites/Blocks/Gray40.png'
bs_dark_red_block = 'Assets/Sprites/Blocks/DarkRed.png'
bs_brown_block = 'Assets/Sprites/Blocks/Brown.png'
bs_magma_block = 'Assets/Sprites/Grass/Magma.png'
bs_gray25_block = 'Assets/Sprites/Blocks/Gray25.png'
bs_emerald_block = 'Assets/Sprites/Blocks/Emerald.png'
bs_yellow_block = 'Assets/Sprites/Blocks/Yellow.png'
bs_masher_col = 'Assets/Sprites/Extra1/HellStuff/Collumn.png'
# Images of circles
bs_red_circle = 'Assets/Sprites/Circles/Red_pixian_ai.png'
bs_green_circle = 'Assets/Sprites/Circles/Green_pixian_ai.png'
bs_yel_brown_circle = 'Assets/Sprites/Circles/YellowBrown_pixian_ai.png'
# Blood
bs_bld_drip = 'Assets/Sprites/Blood/Drip_pixian_ai.png'
bs_bld_puddle = 'Assets/Sprites/Blood/Puddle_pixian_ai.png'
bs_bld_stain1 = 'Assets/Sprites/Blood/Stain1_pixian_ai.png'
bs_bld_stain2 = 'Assets/Sprites/Blood/Stain2_pixian_ai.png'
# Fire
bs_stg1 = 'Assets/Sprites/Fire/1_pixian_ai.png'
bs_stg2 = 'Assets/Sprites/Fire/2_pixian_ai.png'
bs_stg3 = 'Assets/Sprites/Fire/3_pixian_ai.png'
bs_stg4 = 'Assets/Sprites/Fire/4_pixian_ai.png'
bs_stg5 = 'Assets/Sprites/Fire/5_pixian_ai.png'
bs_stg6 = 'Assets/Sprites/Fire/6_pixian_ai.png'
# Sounds
bs_collect_snd = 'Assets/Music/Action/Crystall.ogg'
bs_burning_snd = 'Assets/Music/Action/Burning.ogg'
bs_col_laser_snd = 'Assets/Music/Action/Collide_laser.ogg'
bs_col_block_bl_snd = 'Assets/Music/Action/Rock_to_rock.ogg'
bs_smash_snd = 'Assets/Music/Action/Smash_dead.ogg'
